In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv("train.csv")
df

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995      0       0       0       0       0       0       0       0       0   
41996      1       0       0       0       0       0       0       0       0   
41997      7       0       0       0       0       0       0       0       0   
41998      6       0       0       0       0       0       0       0       0   
41999      9       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 785 columns]

In [7]:
y  = df['label']

In [8]:
df_new = df.drop("label",axis=1)

In [9]:
df_new

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995       0       0       0       0       0       0       0       0       0   
41996       0       0       0       0       0       0       0       0       0   
41997       0       0       0       0       0       0       0       0       0   
41998       0       0       0       0       0       0       0       0       0   
41999       0       0       0       0       0       0       0       0       0   

       pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 784 columns]

In [42]:
X_train1 = df_new.to_numpy()

In [43]:
X_train1

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [44]:
y_train1 = y.to_numpy()

In [45]:
y_train1

array([1, 0, 1, ..., 7, 6, 9], dtype=int64)

In [46]:
from sklearn.model_selection import train_test_split
X_train, y_train, X_test, y_test = train_test_split(X_train1, y_train1,test_size = 0.2, random_state= 2)

In [32]:
class custom_PCA:
    def fit(self,X_train,n_comp):
        self.n_comp = n_comp
        X_meaned = X_train-np.mean(X_train,axis=0)
        cov_mat = np.cov(X_meaned, rowvar = False)
        eigen_values , eigen_vectors = np.linalg.eigh(cov_mat)
        sorted_index = np.argsort(eigen_values)[::-1]
        sorted_eigenvalue = eigen_values[sorted_index]
        sorted_eigenvectors = eigen_vectors[:,sorted_index]
        eigenvector_subset = sorted_eigenvectors[:,0:n_comp]
        X_reduced = np.dot(eigenvector_subset.transpose(),X_meaned.transpose()).transpose()
        return X_reduced

In [33]:
clf = custom_PCA()

In [34]:
X_transformed = clf.fit(X_train,5)

In [35]:
X_transformed

array([[  661.59577975,  -699.31132821,   183.28203965,   120.61139445,
           81.08181052],
       [-1701.4516848 ,  -360.5515562 ,  -501.80559391,   335.42365557,
          442.37893255],
       [  886.89443411,  -293.76578219,    67.15530988,    78.26376284,
          473.71592144],
       ...,
       [ -336.26998171,   950.01528029,  -168.60541437,  -692.68096274,
          539.36384339],
       [ -327.39939154,    62.01608944,   697.53640055,   482.81043924,
          154.81377834],
       [  364.24919987,   418.89302645,    62.89982318,    77.58032347,
          -54.86608748]])

In [36]:
from scipy.stats import mode

In [ ]:
class custom_kNN:
    def dist(self,row1,row2):
        di = np.sqrt(np.sum((row1-row2)**2))
        return di
    def fit(self,X_train,k):
        labels = []
        for i in X_test:
            i_dist = []
            for j in range(len(X_train)):
                dis = self.dist(np.array(X_train[j,:]) , i)
                i_dist.append(dis)
            i_dist = np.array(i_dist)
            dist_new = np.argsort(i_dist)[:k]
            labe = y[dist_new]
            lab = mode(labe)
            lab = lab.mode[0]
            labels.append(lab)
        return labels

In [ ]:
new_clf = custom_kNN()


In [ ]:
y_pred = new_clf.fit(X_train,y_train,X_test,7)

In [ ]:
def acc_score(actual,predicted):
    correct = 0
    for i in range(len(actual)):
        if(actual[i]==predicted[i]):
            correct = correct +1
    return (correct/len(actual))*100.0

In [ ]:
print(acc_score(y_train,y_pred))

In [ ]:
clf2 = custom_kNN()
y_pred2 = clf2(X_transformed)
print(acc_score(y_train,y_pred2))